In [32]:
import numpy as np
import pickle
import pandas as pd




tcLab = pd.read_pickle('TCLab_Down_sampling001_1000.pkl') # Put the original name

downsampled_interval = 30 # New interval (sec)



tcLab_resample = tcLab.iloc[::downsampled_interval, :]

print(tcLab_resample) # Check the file

tcLab_resample.to_pickle('Down_TCLab_MIMO_Data_001_1000_30s.pkl') # New name for down sample file

            H1         H2     T1     T2
1     0.000000   0.000000  24.12  22.96
31    0.000000   0.000000  24.12  22.93
61    0.000000   0.000000  24.22  22.93
91    0.000000  66.000000  24.25  23.61
121  68.000000  66.000000  29.18  26.73
151  68.000000  66.000000  38.69  30.60
181  68.000000  66.000000  47.39  34.95
211  68.000000  66.000000  54.61  38.95
241  68.000000  66.000000  60.54  42.75
271  68.000000  66.000000  65.24  45.94
301  68.000000  66.000000  69.30  48.68
331  68.000000  66.000000  72.33  50.80
361  68.000000  66.000000  74.85  53.13
391   0.000000  57.574413  75.49  54.41
421   0.000000  57.574413  68.98  55.64
451  43.800733  57.574413  60.86  53.67
481  43.800733  57.574413  59.63  53.45
511  43.800733  57.574413  57.77  51.38
541  43.800733  57.574413  57.67  50.68
571  43.800733  57.574413  58.31  49.71
601  43.800733  57.574413  59.70  50.32
631  43.800733  57.574413  60.28  51.45
661  43.800733  57.574413  60.60  51.00
691  43.800733  53.165079  60.92  51.13
721  43.800733  53.165079  61.21  51.16
751  43.800733  53.165079  62.08  51.19
781  43.800733  53.165079  61.12  50.87
811  43.800733  53.165079  60.60  50.84
841  43.800733  53.165079  60.31  50.10
871  43.800733  53.165079  60.63  50.10
901  43.800733  53.165079  61.25  50.22
931  43.800733  53.165079  61.79  50.74
961  43.800733  53.165079  62.47  51.32
991  43.800733  53.165079  61.54  52.09

In [28]:
sequence_interval = 1 # Original interval (sec)
downsampled_interval = 30 # New interval that we want (sec)
step_size = np.round(downsampled_interval / sequence_interval).astype("int")


talab_resample = talab.iloc[::step_size, :]
print(talab_resample)

            H1         H2     T1     T2
1     0.000000   0.000000  24.12  22.96
31    0.000000   0.000000  24.12  22.93
61    0.000000   0.000000  24.22  22.93
91    0.000000  66.000000  24.25  23.61
121  68.000000  66.000000  29.18  26.73
151  68.000000  66.000000  38.69  30.60
181  68.000000  66.000000  47.39  34.95
211  68.000000  66.000000  54.61  38.95
241  68.000000  66.000000  60.54  42.75
271  68.000000  66.000000  65.24  45.94
301  68.000000  66.000000  69.30  48.68
331  68.000000  66.000000  72.33  50.80
361  68.000000  66.000000  74.85  53.13
391   0.000000  57.574413  75.49  54.41
421   0.000000  57.574413  68.98  55.64
451  43.800733  57.574413  60.86  53.67
481  43.800733  57.574413  59.63  53.45
511  43.800733  57.574413  57.77  51.38
541  43.800733  57.574413  57.67  50.68
571  43.800733  57.574413  58.31  49.71
601  43.800733  57.574413  59.70  50.32
631  43.800733  57.574413  60.28  51.45
661  43.800733  57.574413  60.60  51.00
691  43.800733  53.165079  60.92  51.13
721  43.800733  53.165079  61.21  51.16
751  43.800733  53.165079  62.08  51.19
781  43.800733  53.165079  61.12  50.87
811  43.800733  53.165079  60.60  50.84
841  43.800733  53.165079  60.31  50.10
871  43.800733  53.165079  60.63  50.10
901  43.800733  53.165079  61.25  50.22
931  43.800733  53.165079  61.79  50.74
961  43.800733  53.165079  62.47  51.32
991  43.800733  53.165079  61.54  52.09